### PR TITLE
Route to initiate playback script and UI update

### PR DESCRIPTION
**Pull request by ebtskin**
Added new routes in express server to handle playback script. Improved UI for capture forms. Started merging React app with Express server.

### CODE REVIEW

**Review by cdd2 — APPROVED** [review]

**Comment by huanxiangsu** [comment]
I think you re-pushed ui code, it's already in /src folder

**Comment by ebtskin** [comment]
huan, I made some changes.

**Comment by ebtskin** [comment]
I moved the playback plugin Chris was working on into the backEnd (express server) folder to create a route for the playback script. I also moved some of the src folder UI stuff into the backEnd folder so we can host the react front end from the express server. I made some changes to the original UI as well.

**Comment by ebtskin** [comment]
I removed some of the src from backEnd as requested. I left the Playback.js and the plugins folder dependecies in the backEnd because I'm using it for playback. It could also be removed as well. Just let me know. Thanks.

**Review by huanxiangsu — APPROVED** [review]

**Pull request merged**
